profile: local

server:
  port: 80

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2 # H2 Console의 Path
      settings:
        trace: false                        # Print additional trace information
        web-allow-others: true    # 브라우저로 접근가능하게 하기
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용
    url: jdbc:h2:mem:henrydb;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: sa # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)


datasource:
  hs:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용
    jdbc-url: jdbc:h2:mem:henrydb;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: sa # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  emma:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용
    jdbc-url: jdbc:h2:mem:henrydb;DB_CLOSE_DELAY=-1 # userdb 스키마에 mem인 메모리 데이터 베이스로 동작
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: sa # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

notion:
  api-key: secret_t9s28bGo38SuGmZfB6V08KAANZtgiCJmoJNSuq4O5g6